trigger:
  - none

pool: 
  name: Anushrut-SHA-Pool

stages:
  - stage: Terraform_Init   # Spaces not allowed in stage and job names
    jobs:
      - job: TerraformInit_Job
        displayName: Terraform Init-Job
        steps:
          - script: 
              echo Terraform Init Completed.

  - stage: Terraform_FMT
    dependsOn: Terraform_Init
    jobs:
      - job: Terraformfmt_Job
        displayName: Terraform fmt-Job
        steps:
          - script: 
              echo Terraform fmt Completed.

  - stage: Terraform_Validate
    dependsOn: Terraform_FMT
    jobs:
      - job: TerraformValidate_Job
        displayName: Terraform Validate-Job
        steps:
          - script: 
              echo Terraform validate Completed.

  - stage: Terraform_Plan
    dependsOn: Terraform_Validate
    jobs:
      - job: TerraformPlan_Job
        displayName: Terraform Plan-Job
        steps:
          - script: 
              echo Terraform Plan Completed.

  - stage: Terraform_Approve
    dependsOn: Terraform_Plan
    # pool: server   # 'TerraformApprove_Job' is a server job, but contains task 'CmdLine' which can only run on agents. 
    jobs:
      - job: TerraformApprove_Job
        displayName: Terraform Approve-Job
        steps:
          - script: 
              echo Terraform Approve Completed.

  - stage: Terraform_Apply
    dependsOn: Terraform_Approve
    jobs:
      - job: TerraformApply_Job
        displayName: Terraform Apply-Job
        steps:
          - script: 
              echo Terraform Apply Completed.